### ISSUE TITLE
about requirements.txt

### ISSUE THREAD

**Issue by SEUvictor** [FeiiYin/StyleHEAT#11]
Why is requirements.txt so much and so messy, and what does '@ file...' mean?

![image](https://user-images.githubusercontent.com/73874553/179942456-138c8f00-da61-4e27-b4ad-9add1c2a0ce5.png)

Can you release a simple and effective version？

**Comment by twilight0718** [comment]
Those '@ file...' probably means that they install the lib by local file.
I just delete all the '@ file...' and it works.

**Comment by FeiiYin** [comment]
Sorry for the mistake, I release a cleaner requirements.txt for reference.
