### ISSUE TITLE
Process freeze!

### ISSUE THREAD

**Issue by harlanhong** [FeiiYin/StyleHEAT#13]
Hi, 

Thanks for your nice work. After I install StyleHEAT and run the command:
`CUDA_VISIBLE_DEVICES=0 python inference.py --config configs/inference.yaml --video_source=./docs/demo/videos/RD_Radio34_003_512.mp4 -output_dir=./docs/demo/output --if_extract`

The process freezes as shown in the following picture:
<img width="755" alt="image" src="https://user-images.githubusercontent.com/19970321/183234173-b30e70e9-72ea-4b87-9609-57e7f9cd26e1.png">

How to solve this problem?

**Comment by FeiiYin** [comment]
That is weird since there is no error reported.
Maybe it is processing the 3DMM extraction. You can print log in inner modules to check which code line it stuck at.
By the way, we recommend using A100 or 3090 to run the code.

**Comment by zvxme** [comment]
did you solve it？
