### ISSUE TITLE
How to train the whole framework?

### ISSUE THREAD

**Issue by Howx99** [FeiiYin/StyleHEAT#14]
Hi, thanks for your nice work. 
I notice that in README, we can train the whole network by running bash bash/train_video_styleheat.sh, but I could not find this file. Also, in utils/trainer.py, a config file(maybe video_styleheat_trainer.yaml ?) is needed to get the model and the trainer. Can you release the training code or the config file for training?

**Comment by FeiiYin** [comment]
Thanks for your attention. 
I released the training part code, which is not that clean. 
You need to modify several path parameters to adapt to your local environment.

**Comment by Howx99** [comment]
Ok, thanks a lot!
