### ISSUE TITLE
A few more files to be released for training..

### ISSUE THREAD

**Issue by pcgreat** [FeiiYin/StyleHEAT#16]
Nice Implementations! I wonder if you can also upload train.py, mirror_warper.py, and a few extra files for training. Thanks in advance

**Comment by aishoot** [comment]
Thanks for your nice work. +1 request.

**Comment by FeiiYin** [comment]
Sorry for the mistake, `train.py` file has been released and the training configs in yaml have been fixed.

**Comment by aishoot** [comment]
> Sorry for the mistake, `train.py` file has been released and the training configs in yaml have been fixed.

Good job~ Thanks.
