### ISSUE TITLE
Facing issue on inferrence

### ISSUE THREAD

**Issue by rohaantahir** [FeiiYin/StyleHEAT#17]
Hi I am trying to run the for the demo purpose of your pretrained and provided files. however upon execution of the command: 

"python inference.py --config configs/inference.yaml --video_source=./docs/demo/videos/RD_Radio34_003_512.mp4 --image_source=./docs/demo/images/100.jpg --cross_id --output_dir=./docs/demo/output"

I am facing the following error.

Stage: inference
Load pre-trained StyleHEAT [net_G_ema] from checkpoints/StyleHEAT_visual.pt done
  0%|                                                                                            | 0/1 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 219, in <module>
    main()
  File "inference.py", line 202, in main
    data = dataset.load_next_video()
  File "D:\rt_faceSync\styleheat\StyleHEAT\data\inference_dataset.py", line 174, in load_next_video
    video_data = self.data_preprocess(video_path, image_path)
  File "D:\rt_faceSync\styleheat\StyleHEAT\data\inference_dataset.py", line 118, in data_preprocess
    source_3dmm = self.model_3dmm.get_3dmm([src_image_pil_256]

**Comment by ccyyatnet** [comment]
add --if_extract

**Comment by rohaantahir** [comment]
Thanks working now

**Comment by rohaantahir** [comment]
@FeiiYin @ccyyatnet can you please tell me how to inference on audio driven lip movement generation?
