### ISSUE TITLE
Dataset preprocess

### ISSUE THREAD

**Issue by youngAt19** [FeiiYin/StyleHEAT#2]
Hi, would you share the processed dataset mentioned in your paper or the preprocessing code? Thanks.

**Comment by youngAt19** [comment]
I want to reproduce the model in your paper and I try to download the voxceleb following [this repo](https://github.com/AliaksandrSiarohin/video-preprocessing), but it seems that some videos are not available now.
`Can not load video EdFbFdf0K7w, broken link`
Could you share the voxceleb dataset used in your experiment by google cloud, baidu netdisk or other software?

**Comment by Luh1124** [comment]
> Hi, would you share the processed dataset mentioned in your paper or the preprocessing code? Thanks.

I have this voxceleb dataset and you can email me

**Comment by FeiiYin** [comment]
> I want to reproduce the model in your paper and I try to download the voxceleb following [this repo](https://github.com/AliaksandrSiarohin/video-preprocessing), but it seems that some videos are not available now.
> (it comes out likes `Can not load video EdFbFdf0K7w, broken link`)
> Could you share the voxceleb dataset used in your experiment by google cloud, baidu netdisk or other software?

We use the [this repo](https://github.com/AliaksandrSiarohin/video-preprocessing) to pre-process the dataset.
Some download links expired and raise the error `Can not load video EdFbFdf0K7w, broken link`.
For 3DMM parameters extraction, we use [Deep3DFaceRecon_pytorch](https://github.com/sicxu/Deep3DFaceRecon_pytorch) to extract.
You can follow [PIRenderer](https://github.com/RenYurui/PIRender) to pre-process the dataset for now.

**Comment by youngAt19** [comment]
Get it :). Thanks

**Comment by youngAt19** [comment]
> > Hi, would you share the processed dataset mentioned in your paper or the preprocessing code? Thanks.
> 
> I have this voxceleb dataset and you can email me

Thank you. I have sent you an email, please check it.
