### ISSUE TITLE
Deep3D checkpoint gone from checkpoints google drive folder?

### ISSUE THREAD

**Issue by rickdotta** [FeiiYin/StyleHEAT#20]
I can't find it here

https://drive.google.com/drive/folders/1BtETxoWlVRoPI6vcySAzimfhemmpc4px

and inference with --if_extract then fails with the following:

FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/Deep3D/epoch_20.pth

**Comment by FeiiYin** [comment]
Please make a directory `Deep3D` and put `epoch_20.pth` from the link into the directory.

**Comment by rickdotta** [comment]
Thank you, just noticed the file was there!
