### ISSUE TITLE
Error while trying inference "Cross-Identity Reenactment with a single image and a video."

### ISSUE THREAD

**Issue by diht404** [FeiiYin/StyleHEAT#21]
I am running 

python inference.py \
 --config configs/inference.yaml \
 --video_source=./docs/demo/videos/RD_Radio34_003_512.mp4 \
 --image_source=./docs/demo/images/100.jpg \
 --cross_id \
 --output_dir=./docs/demo/output

and get the following error. Are there any ways to sole it?
Load pre-trained StyleHEAT [net_G_ema] from checkpoint/StyleHEAT_visual.pt done
  0%|                                                                                    | 0/1 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 219, in <module>
    main()
  File "inference.py", line 202, in main
    data = dataset.load_next_video()
  File "/home/jupyter-terentevvs/StyleHEAT/data/inference_dataset.py", line 174, in load_next_video
    video_data = self.data_preprocess(video_path, image_path)
  File "/home/jupyter-terentevvs/StyleHEAT/data/inference_dataset.py", line 118, in data_preprocess
    source_3dmm = self.model_3dmm.get_3dmm([src_image_pil_256], lm_np)
AttributeError: 'NoneType' object has no attribute 'get_3dmm'

**Comment by FeiiYin** [comment]
Please add `--if_extract` for first inference.

**Comment by diht404** [comment]
Thanks, it works for me!
