### ISSUE TITLE
Worked perfectly on cross-Identity reenactment only if the single image is from ffhq datasets

### ISSUE THREAD

**Issue by Shotsordsoo** [FeiiYin/StyleHEAT#27]
And failed every images that aren't. It looks like the face parts are generated properly, yet the locations are wrong:

https://user-images.githubusercontent.com/16696685/206865487-c1aede3d-d56a-4c55-8bba-22c7f9a8eac8.mp4

![Obama](https://user-images.githubusercontent.com/16696685/206865551-dc68195f-4972-45f8-97e3-2eada1c7f8fb.jpg)

**Comment by FeiiYin** [comment]
Since our framework is based on StyleGAN, we need to perform GAN inversion method to reconstruct the identity image. StyleGAN is trained on aligned high-resolution images, i.e. FFHQ. Therefore, GAN inversion methods, along with our method required aligned data.

**Comment by Shotsordsoo** [comment]
> Since our framework is based on StyleGAN, we need to perform GAN inversion method to reconstruct the identity image. StyleGAN is trained on aligned high-resolution images, i.e. FFHQ. Therefore, GAN inversion methods, along with our method required aligned data.

Thx, work like a charm

**Comment by FeiiYin** [comment]
:-)

**Comment by kmurad-qlu** [comment]
@Shotsordsoo how did you do that, I am getting really bad results , using same id.
