### ISSUE TITLE
some inconsistent in code

### ISSUE THREAD

**Issue by yqwang** [FeiiYin/StyleHEAT#29]
Very appreciate your great work. I maybe found two inconsistent in code when i try to retrain the video warper, but not very uncertainly and hope to make check it. 
1. https://github.com/FeiiYin/StyleHEAT/blob/bad7f124a74028ee4f425428388bb1e350a5119e/trainers/video_warper_trainer.py#L88
I found there is no key 'final_image' in all network forward return results. 
2. https://github.com/FeiiYin/StyleHEAT/blob/bad7f124a74028ee4f425428388bb1e350a5119e/trainers/video_warper_trainer.py#L87
parameters is not equal to defined in VideoWarper::forward

**Comment by FeiiYin** [comment]
Thanks for your attention!
It seems there exist several testing codes in the repo. The `final_image` is used for mixing two warping processes but is not in use in the end. There exist only one output of the video warper. You can delete the code about the `final_image` and only use the `warping_field` to warp the original image or feature.
