### ISSUE TITLE
Ram issue

### ISSUE THREAD

**Issue by LeoLovechest** [FeiiYin/StyleHEAT#31]
I tried 
`python inference.py --config configs/inference.yaml --video_source=./docs/demo/videos/RD_Radio34_003_512.mp4 --image_source=./docs/demo/images/100.jpg --cross_id --output_dir=./docs/demo/output --if_extract`
Got a run out of memory due to only having a 4GB GPU

Tried with a shorter video and my pc slowed down for 30 mins staying at 0% progress
What are my options apart from buying a better GPU?
Can I use CPU for instance?

It could be slowed down due to extracting the 3dmm params so as a newbie how do I run the TODO.sh?

**Comment by FeiiYin** [comment]
4GB GPU may not support the repo. Extracting 3DMM parameters does take quite a time.
You can attempt to move all the modules onto the CPU device via `.to('cpu)`. On that condition, the recommended RAM is about 32 GB memory.
