### ISSUE TITLE
"Killed" Error 

### ISSUE THREAD

**Issue by m-pektas** [FeiiYin/StyleHEAT#32]
Hi, I try to run this repository. But, I get just "Killed" text in my terminal. 

### Output:
![bug](https://user-images.githubusercontent.com/15729405/212670671-c4ba20b6-139d-4a62-ad17-6693e23b1346.png)

### Environment
**GPU :** RTX 3050
**NVIDIA Driver :** 510.108.03
**Cuda :** 11.6

You can find the packages in my environment from [here](https://github.com/FeiiYin/StyleHEAT/files/10425304/requirements_local.txt).

**Comment by FeiiYin** [comment]
I guess the problem may be raised from running out of RAM. What is your memory environment, 32GB or higher?

**Comment by m-pektas** [comment]
> I guess the problem may be raised from running out of RAM. What is your memory environment, 32GB or higher?

Actually, I have 16gb RAM.

**Comment by m-pektas** [comment]
Also, I tried to run the project in colab. I got the following output. The cell is finished but there is no output in the output folder.
![bug-colab](https://user-images.githubusercontent.com/15729405/212680649-25651b31-a0d3-48ca-b586-90767b6bb47d.png)

**Comment by FeiiYin** [comment]
16gb RAM may support the repo, you can try to run with a shorter guided video, like 1 second.
The output of the colab looks fine. The inference code will save the video into the output folder. You can download the video for further usage.

**Comment by m-pektas** [comment]
Thanks for your reply @FeiiYin. When I tried the 2 second video, "Killed" error changed and I got the cuda out of memory. I gonna run the code on vm that have high ram and gpu memory. I will write the results here.

**Comment by m-pektas** [comment]
I tried to run on VM that has high RAM(60gb) and 16gb gpu memory. It worked correctly with both long and short driving videos. Thanks for your help.
