### ISSUE TITLE
How much GPU memory is required at least?

### ISSUE THREAD

**Issue by Pythonpa** [FeiiYin/StyleHEAT#35]
Thank you for your excellent work. 
Does anyone know how much GPU memory is required at least?
My Nvidia RTX  8GB，can't work......CUDA out of memory............sad

**Comment by leoingva** [comment]
my GMEM is 6G, can run SadTalker, but out of memory here..........sad

**Comment by Hujiazeng** [comment]
12G can run well, by the way, RAM as important as GPU.

**Comment by Pythonpa** [comment]
OK，GOT IT ,THKS AGAIN
