### ISSUE TITLE
The output video of the inference does not have sound

### ISSUE THREAD

**Issue by Jeriousman** [FeiiYin/StyleHEAT#46]
I can hear nothing from the generated output video after inferencing as below. The video seems to be fine but only sound is missing.

```
python inference.py \
 --config configs/inference.yaml \
 --video_source=./docs/demo/videos/RD_Radio34_003_512.mp4 \
 --output_dir=./docs/demo/output --if_extract
```

Is it only me who got the issue? Or if there was anyone who got the same problem, please comment below. Thanks!

**Comment by FeiiYin** [comment]
Please first install SadTalker in the folder of third_part as the format of third_part/SadTalker. Download its pre-trained checkpoints according to their instructions. Install the additional libraries with pip install pydub==0.25.1 yacs==0.1.8 librosa==0.6.0 numba==0.48.0 resampy==0.3.1 imageio-ffmpeg==0.4.7. Then you can run audio reenactment with the following script.
```
python inference.py \
 --config configs/inference.yaml \
 --audio_path=./docs/demo/audios/RD_Radio31_000.wav \
 --image_source=./docs/demo/images/100.jpg \
 --cross_id --if_extract \
 --output_dir=./docs/demo/output \
 --inversion_option=optimize
```
